Add http-kafka asyncapi example
aklivity/zilla-examples pull request #135
Opened 2024-06-03 12:27 UTC by bmaidics

2024-06-03 12:30 UTC, bmaidics commented
Should only be merged once https://github.com/aklivity/zilla/pull/1072 is merged and released in Zilla.

2024-06-05 02:08 UTC, jfallows requested changes

2024-06-05 02:08 UTC, jfallows commented on http.kafka.asyncapi.proxy/README.md
Rename scenario to `asyncapi.http.kafka.proxy` instead.

All `asyncapi` examples should follow this naming convention.

2024-06-05 02:08 UTC, jfallows commented on http.kafka.asyncapi.proxy/README.md
> +# http.kafka.asyncapi.proxy
This will need to adjust to the new name.

2024-06-05 02:08 UTC, jfallows commented on http.kafka.asyncapi.proxy/README.md
> +Wether you chose [compose](./docker/compose) or [helm](./k8s/helm), the `setup.sh` script will:
```suggestion
Whether you chose [compose](./docker/compose) or [helm](./k8s/helm), the `setup.sh` script will:
```

2024-06-05 02:08 UTC, jfallows commented on http.kafka.asyncapi.proxy/docker/compose/teardown.sh
> +NAMESPACE="${NAMESPACE:-zilla-http-kafka-asyncapi-proxy}"
Please check all scripts etc for rename of example scenario.

2024-06-05 12:35 UTC, vordimous commented on asyncapi.http.kafka.proxy/docker/compose/docker-compose.yaml
> -    pull_policy: always
pull_policy is needed when the build isn't a local build. probably best to just comment it out in the future.

2024-06-07 16:35 UTC, jfallows approved these changes

2024-06-07 17:13 UTC, vordimous approved these changes

2024-06-14 14:08 UTC, vordimous requested changes

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/Dockerfile
> +ENTRYPOINT ["/usr/app/node_modules/.bin/sse-server"]
You can delete this file. I added an sse-server image: https://github.com/aklivity/zilla-demos/pkgs/container/extras-sse-server

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/chart/templates/service-sse-server.yaml
> +          image: "zilla-examples/sse-server:latest"
```suggestion
          image: "ghcr.io/aklivity/extras-sse-server:sha-42ad67e"
```

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/chart/templates/service-sse-server.yaml
> +          image: "zilla-examples/sse-server:latest"
This is the same code just with the image published to your package registry

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/setup.sh
> +docker image inspect zilla-examples/sse-server:latest --format 'Image Found {{.RepoTags}}'
you can remove this.

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/README.md
> +### Build the sse-server docker image
don't need to do this step anymore

2024-06-14 14:08 UTC, vordimous commented on asyncapi.sse.proxy/setup.sh
> +docker image inspect zilla-examples/sse-server:latest --format 'Image Found {{.RepoTags}}'
```suggestion
```

2024-06-14 14:09 UTC, vordimous commented on asyncapi.sse.proxy/README.md
> +
```suggestion
```

2024-07-01 17:19 UTC, merged