Add asyncapi.sse.proxy
aklivity/zilla-examples pull request #138
Opened 2024-06-13 09:46 UTC by bmaidics

2024-06-13 09:46 UTC, bmaidics commented
Depends on https://github.com/aklivity/zilla/pull/1092 and https://github.com/aklivity/zilla/pull/1085

2024-06-18 14:36 UTC, jfallows approved these changes

2024-06-19 12:26 UTC, vordimous commented on asyncapi.sse.proxy/README.md
> +docker build -t zilla-examples/sse-server:latest .
you can reuse the docker image instead of needing to build one.

2024-06-19 13:10 UTC, vordimous requested changes

2024-07-01 15:54 UTC, vordimous approved these changes

2024-07-01 16:19 UTC, merged